language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.12
  - 2.12.7

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - travis_retry sbt ++$TRAVIS_SCALA_VERSION test
